# Connect Kubernetes to AWS Secrets Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: student-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1

---

# Sync DB credentials from AWS Secrets Manager
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-external-secret
  namespace: student-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: mariadb-secret
    creationPolicy: Owner

  # Copy DB_URL, DB_USERNAME and DB_PASSWORD
  # directly from AWS Secrets Manager
  dataFrom:
    - extract:
        key: student-app/mariadb-secret